### ISSUE TITLE
oooops!

### ISSUE THREAD

**Issue by PenguinOwl** [B1G-FUNGUS/winfoc#2]
i tried the steps and the step 3 failed before it could finish!! i got an error
```
[create settings.mk]
[check reqs]
Missing requirement: lzip

Please have a look at "docs/index.html" to ensure
that your system meets all requirements.

make: *** [Makefile:456: /home/henry/repos/mxe/usr/installed/check-requirements] Error 1
```

**Comment by B1G-FUNGUS** [comment]
Make sure you have all the needed requirements installed.
This step was added to the README in ae77d28145d9c3ce22e33d7071a19bb66baf394a.
